//
//  Translate.swift
//  Tracker
//
//  Created by Maksim Zimens on 03.02.2024.
//

import Foundation

struct Translate {
    static let tabBarTitleTrecker = NSLocalizedString("trackers", comment: "")
    static let tabBarTitleStatistic = NSLocalizedString("statistics", comment: "")
    static let textLableTwoVC = NSLocalizedString("textLableTwoVC", comment: "")
    static let textButton = NSLocalizedString("textButton", comment: "")
    static let headerText = NSLocalizedString("headerText", comment: "")
    static let labelStabText = NSLocalizedString("labelStabText", comment: "")
    static let labelNothingFoundText = NSLocalizedString("labelNothingFoundText", comment: "")
    static let placeholderSearch = NSLocalizedString("placeholderSearch", comment: "")
    static let textCancel = NSLocalizedString("textCancel", comment: "")
    static let textFix = NSLocalizedString("textFix", comment: "")
    static let textUnpin = NSLocalizedString("textUnpin", comment: "")
    static let textEdit = NSLocalizedString("textEdit", comment: "")
    static let textDelete = NSLocalizedString("textDelete", comment: "")
    static let textFixed = NSLocalizedString("textFixed", comment: "")
    static let sureDeleteTracker = NSLocalizedString("sureDeleteTracker", comment: "")
    static let filters = NSLocalizedString("filters", comment: "")
    static let headerStatisticText = NSLocalizedString("headerStatisticText", comment: "")
    static let secondaryStatisticText = NSLocalizedString("secondaryStatisticText", comment: "")
    static let labelStubStatisticsText = NSLocalizedString("labelStubStatisticsText", comment: "")
    static let newHabit = NSLocalizedString("newHabit", comment: "")
    static let newIrregular = NSLocalizedString("newIrregular", comment: "")
    static let numberOfDays = NSLocalizedString("numberOfDays", tableName: "LocalizableDict", comment: "")
    static let placeholderTrackerTextField = NSLocalizedString("placeholderTrackerTextField", comment: "")
    static let textCancelButton = NSLocalizedString("textCancelButton", comment: "")
    static let textGreateButton = NSLocalizedString("textGreateButton", comment: "")
    static let characterLimit = NSLocalizedString("characterLimit", comment: "")
    static let everyDay = NSLocalizedString("everyDay", comment: "")
    static let scheduleLableText = NSLocalizedString("scheduleLableText", comment: "")
    static let doneButtonText = NSLocalizedString("doneButtonText", comment: "")
    static let categoryLabelText = NSLocalizedString("categoriLabelText", comment: "")
    static let categoryAddButtonText = NSLocalizedString("categoriAddButtonText", comment: "")
    static let alertDeleteCategoryMessage = NSLocalizedString("deleteCategoryMessage", comment: "")
    static let texGreatetLabelName = NSLocalizedString("texGreatetLabelName", comment: "")
    static let newcategoriLabelText = NSLocalizedString("newcategoriLabelText", comment: "")
    static let buttonName = NSLocalizedString("buttonName", comment: "")
    static let placeholderCategoryTextField = NSLocalizedString("placeholderCategoryTextField", comment: "")
    static let filtersLableText = NSLocalizedString("filters", comment: "")
    static let textLable = NSLocalizedString("textLableOneVC", comment: "")
    static let monday = NSLocalizedString("monday.complete", comment: "")
    static let tuesday = NSLocalizedString("tuesday.complete", comment: "")
    static let wednesday = NSLocalizedString("wednesday.complete", comment: "")
    static let thursday = NSLocalizedString("thursday.complete", comment: "")
    static let friday = NSLocalizedString("friday.complete", comment: "")
    static let saturday = NSLocalizedString("saturday.complete", comment: "")
    static let sunday = NSLocalizedString("sunday.complete", comment: "")
    static let briefMonday = NSLocalizedString("monday", comment: "")
    static let briefTuesday = NSLocalizedString("tuesday", comment: "")
    static let briefWednesday = NSLocalizedString("wednesday", comment: "")
    static let briefThursday = NSLocalizedString("thursday", comment: "")
    static let briefFriday = NSLocalizedString("friday", comment: "")
    static let briefSaturday = NSLocalizedString("saturday", comment: "")
    static let briefSunday = NSLocalizedString("sunday", comment: "")
    static let category = NSLocalizedString("category", comment: "")
    static let schedule = NSLocalizedString("schedule", comment: "")
    static let nameHabit = NSLocalizedString("nameHabit", comment: "")
    static let nameIrregularEvent = NSLocalizedString("nameIrregularEvent", comment: "")
    static let colorHeader = NSLocalizedString("stringColor", comment: "")
    static let decodingErrorInvalidNameCategory = NSLocalizedString("decodingErrorInvalidNameCategory", comment: "")
    static let getCategoryCoreDataError = NSLocalizedString("getCategoryCoreDataError", comment: "")
    static let getTrackerError = NSLocalizedString("getTrackerError", comment: "")
    static let decodingErrorInvalidName = NSLocalizedString("decodingErrorInvalidName", comment: "")
    static let decodingErrorInvalidId = NSLocalizedString("decodingErrorInvalidId", comment: "")
    static let decodingErrorInvalidColor = NSLocalizedString("decodingErrorInvalidColor", comment: "")
    static let decodingErrorInvalidEmoji = NSLocalizedString("decodingErrorInvalidEmoji", comment: "")
    static let decodingErrorInvalidSchedul = NSLocalizedString("decodingErrorInvalidSchedul", comment: "")
    static let transformationErrorInvalid = NSLocalizedString("transformationErrorInvalid", comment: "")
    static let decodingErrorInvalidDate = NSLocalizedString("decodingErrorInvalidDate", comment: "")
    static let loadTrackerRecord = NSLocalizedString("loadTrackerRecord", comment: "")
    static let getTrackerRecord = NSLocalizedString("getTrackerRecord", comment: "")
    static let allTrackers = NSLocalizedString("allTrackers", comment: "")
    static let toDayTrackers = NSLocalizedString("toDayTrackers", comment: "")
    static let completed = NSLocalizedString("completed", comment: "")
    static let notCompleted = NSLocalizedString("notCompleted", comment: "")
    static let bestPeriod = NSLocalizedString("bestPeriod", comment: "")
    static let perfectDays = NSLocalizedString("perfectDays", comment: "")
    static let trackersCompleted = NSLocalizedString("trackersCompleted", comment: "")
    static let averageValue = NSLocalizedString("averageValue", comment: "")
}
